### ISSUE TITLE
Refactor code (Smart & Dump components)

### ISSUE THREAD

**Issue by infernalslam** [Sellsuki/kradan#33]

**Comment by n9ti** [comment]
มันไม่จำเป็นต้องทำเป็น Smart & Dump ก็ได้นะครับ
เพราะบางงานก็อาจจะไม่เหมาะ
ลองดูว่าอยากจะ refact ตรงไหนมาดีกว่า แล้วสร้าง issue เพื่อเสนอมา

**Comment by infernalslam** [comment]
เศร้าเลย ....

**Comment by n9ti** [comment]
ลองเสนอมาว่าอยากแก้อะไร ตรงไหน และ เพราะอะไร?
เปิดเป็น issue ใหม่เลย
เดี๋ยวผมขอ issue นี้ก่อนนะ
